[package]
name = "server_result"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
regex = "1.10.4"
reqwest = { version = "0.12.1", features = ["blocking", "json"] }
tokio = { version = "1.36.0", features = ["full"] }
