name: Updating the Json

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build steps here

      - name: Check if latest.json exists
        run: test -f latest.json
        continue-on-error: true
        id: check_latest_json

      - name: Generate latest.json
        if: steps.check_latest_json.outcome != 'success'
        run: |
          curl -LJO https://github.com/kamranmuazzam/im19result/releases/download/v0.156.0/latest.json

      - name: Configure Git
        run: |
          git config --global user.email "kamranmuazzam@gmail.com"
          git config --global user.name "kamran_muazzam"

      - name: Commit changes
        run: |
          git add latest.json
          git commit -m "Move latest.json to root"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

    # Add any other steps as needed
