name: test host

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  open-port:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          sudo apt update
          sudo apt install apache2
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "kamranmuazzam@gmail.com"
          git config --global user.name "kamran_muazzam"
          git pull origin main
      - name: Display Public IP
        run: |
          curl ifconfig.me
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install http-server -g

      - name: Open Port
        run: |
          sudo ufw allow 3000
      - name: Display Public IP
        run: |
          echo "Public IP:"
          curl ifconfig.me
      - name: Determine Router IP
        id: router_ip
        run: |
          # Fetch the default gateway using the `ip route` command and extract the router IP address
          ROUTER_IP=$(ip route | awk '/default/ { print $3 }')
          echo "::set-output name=router_ip::$ROUTER_IP"

      - name: Open Port on Router
        run: |
          ssh admin@${{ steps.router_ip.outputs.router_ip }} "iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 3000 -j DNAT --to 10.1.1.84:3000"
          - name: Build and deploy
      - name: Building and deploying website
        run: |
          echo "Building and deploying website..."
          mkdir -p deploy
          cp index.html deploy/
          cd deploy
          npx http-server -p 3000

      - name: Finalize Deployment
        run: |
          echo "Website deployed successfully!"
      - name: Start Server
        run: |
          while true; do
              # Your commands to run here
              echo "Running your server..."
              sleep 10
          done
