name: Open Port on Device IP

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  open-port:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          sudo apt update
          sudo apt install apache2
      - name: Display Public IP
        run: |
          curl ifconfig.me
      - name: a loop
        run: |
          while true; do
              # Your commands to run here
              echo "Running your commands..."
              # For example, you can replace the echo command above with the commands you want to run.

              # Wait for 10 seconds
              sleep 10
          done
