name: Open Port on Device IP

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  open-port:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          sudo apt update
          sudo apt install apache2
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "kamranmuazzam@gmail.com"
          git config --global user.name "kamran_muazzam"
          git pull origin main
      - name: Display Public IP
        run: |
          curl ifconfig.me
      - name: Open Port
        run: |
          sudo nc -l -p 8080 &
      - name: Display index.html file
        run: |
          ls
          cat index.html
      - name: Start Server
        run: |
          while true; do
              # Your commands to run here
              echo "Running your server..."
              sleep 10
          done
