name: Update Result of IM-19

on:
  push:
    branches:
      - main # Modify this to match your branch name

jobs:
  pentagon:
    name: run on mac
    runs-on: macos-latest
    strategy:
      matrix:
        repeat:
          - 1
          - 2
          - 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Checking Results
        run: |
          ./server_result/target/x86_64-apple-darwin/debug/server_result
